name: Build BioCollect PWA Artifacts

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - 'main'
      - 'testing'

jobs:
  build-and-attach:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install

      - name: Build app for CICD
        run: pnpm run build:cicd

      - name: Upload production artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-production
          path: dist/app-production.zip

      - name: Upload staging artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-staging
          path: dist/app-staging.zip

      - name: Upload testing artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-test
          path: dist/app-test.zip

      - name: Upload development artifact
        uses: actions/upload-artifact@v7
        with:
          name: app-dev
          path: dist/app-dev.zip
